%YAML:1.0
---
cameraMatrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 643.911329436429, 0., 448.7322537894622,
           0., 647.6219233699345, 239.3461615375938,
           0., 0., 1. ]
distCoeffs: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ -0.008434335222284635, 0.2768387981846273, 0.0006404635827151714, 0.00501406505258983, -0.4991903010039486 ]